# See https://pre-commit.com for more information
ci:
  skip: [prettier]

repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry:
          corepack npm exec --package=prettier -- prettier --cache
          --ignore-unknown --write
        language: system
