exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - '.jekyll-cache'

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: "Pikaviestin.fi ylläpitäjät" # jekyll-seo-tag > default author
#social: # jekyll-seo-tag > social overrides
#  name: David Darnes # jekyll-seo-tag > real name
#  links:  # jekyll-seo-tag > social aliases (sameAs)
#    - https://twitter.com/DavidDarnes
#    - https://www.facebook.com/daviddarnes
#    - https://www.linkedin.com/in/daviddarnes
#    - https://github.com/daviddarnes
#markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Helsinki # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Uusimmat # Needed for Siteleaf
    output: true
    description: "Mitä meille kuuluu?" # The post list page content
    feature_text: |
      ## Tuoreimmat päivitykset
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/space-blur.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: fi-FI # Set the site language
title: "pikaviestin.fi" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/vp_ikoni_b.png" # Site logo, also used in jekyll-seo-tag
description: "Pikaviestin.fi on Suomalaisille käyttäjille suunnattu ilmainen Matrix-verkon pikaviestipalvelu." # Site description and default description, also used in jekyll-seo-tag
url: "https://www.pikaviestin.fi" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/daviddarnes/alembic"
email: "yllapito@pikaviestin.fi"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
date_format: "%d.%m.%Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

destination: ./build

# 8. Site favicons & manifest icons

# Nää ei tee mitään.
#favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
#  16: '/assets/favicon.ico'
#  32: '/assets/favicon.ico'
#  96: '/assets/favicon.ico'
#  120: '/assets/favicon.ico'
#  144: '/assets/favicon.ico'
#  180: '/assets/favicon.ico'
#  515: '/assets/favicon.ico'
#  1024: '/assets/favicon.ico'

# 9. Site navigation
navigation_header:
- title: Etusivu
  url: /
- title: Matrix
  url: /matrix/
- title: Mastodon
  url: /mastodon/
- title: Mobilizon
  url: /mobilizon/
- title: Uutiset
  url: /blog/
- title: Tietosuojaseloste
  url: /tietosuojaseloste.pdf

navigation_footer:
- title: Kapsi Internet-käyttäjät ry
  url: https://www.kapsi.fi
  image: "/assets/logos/kapsi.svg"
  intro: Tekniset resurssit tarjoaa

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/pikaviestin
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#  Twitter: "#0d94e7"
#  facebook: "#3B5998"
#  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
#fonts:
#  preconnect_urls:
#    - https://fonts.gstatic.com
#  font_urls:
#    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
#    - https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap
#    - https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300..800;1,300..800
