name: Jekyll Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Ruby
        uses: ruby/setup-ruby@97e35c5302afcf3f5ac1df3fca9343d32536b286 # v1.184.0
        with:
          ruby-version: '.ruby-version' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Generate PDF of Tietosuojaseloste
        run: corepack npx md-to-pdf tietosuojaseloste.md
        uses:
          - actions/checkout@master
          - actions/setup-node@v4
        with:
          - node-version: lts
          - cache: 'npm'
      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Publish site
        uses: actions-js/push@v1.3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         directory: build
         branch: gh-pages
         force: true
         message: 🧪 Deploy with ${GITHUB_WORKFLOW}
